In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('insurance.csv')
df_new = df.copy()
df_new['age'] = df['age']/100
df_new

     age  affordibility  bought_insurance
0   0.22              1                 0
1   0.25              0                 0
2   0.47              1                 1
3   0.52              0                 0
4   0.46              1                 1
5   0.56              1                 1
6   0.55              0                 0
7   0.60              0                 1
8   0.62              1                 1
9   0.61              1                 1
10  0.18              1                 0
11  0.28              1                 0
12  0.27              0                 0
13  0.29              0                 0
14  0.49              1                 1
15  0.55              1                 1
16  0.25              0                 1
17  0.58              1                 1
18  0.19              0                 0
19  0.18              1                 0
20  0.21              1                 0
21  0.26              0                 0
22  0.40              1                 1
23  0.45              1                 1
24  0.50              1                 1
25  0.54              1                 1
26  0.23              1                 0
27  0.46              1                 0

In [3]:
x_train, x_test, y_train, y_test = train_test_split(df_new[['age', 'affordibility']], df_new['bought_insurance'], train_size=0.8, random_state=10)

In [19]:
class my_NN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
        
    def fit(self, x, y, epochs):
        self.w1, self.w2, self.bias =  self.GradientDescent(x['age'], x['affordibility'], y, epochs)
        print(f"Final Weights: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def evaluate(self, x):
        weighted_sum = self.w1*x['age'] + self.w2*x['affordibility'] + self.bias
        print(self.sigmoid(weighted_sum))
    
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def logloss(self, y_predicted, y_true):
        epsilon = 1e-16
        y_predicted_new = [max(i,epsilon) for i in y_predicted]
        y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
        y_predicted_new = np.array(y_predicted_new)
    
        return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
    
    def GradientDescent(self, age, affordibility, y_true, epochs):
        n = len(age)
        rate = 0.5
        for i in range(epochs):
            weighted_sum = (self.w1*age + self.w2*affordibility + self.bias)
            prediction = self.sigmoid(weighted_sum)
            loss = self.logloss(prediction, y_true)

            w1d = (1/n)*np.dot(np.transpose(age), (prediction-y_true))
            w2d = (1/n)*np.dot(np.transpose(affordibility), (prediction-y_true))
            bd = np.mean(prediction-y_true)

            self.w1 -= rate*w1d
            self.w2 -= rate*w2d
            self.bias -= rate*bd
            
            if (i+1)%100 == 0 or i == 0:
                print(f"w1: {self.w1}, w2: {self.w2}, bias: {self.bias}, loss: {loss} epochs:{i+1}")
        
        return self.w1, self.w2, self.bias
    
custom_model = my_NN()
custom_model.fit(x_train, y_train, 500)

w1: 0.9710141176354745, w2: 0.9345848053389119, bias: -0.12223535107481856, loss: 0.7310655342076743 epochs:1
w1: 2.0639097625466922, w2: 1.3949777088460362, bias: -1.7924083641380144, loss: 0.5383911700189136 epochs:100
w1: 3.223526571172989, w2: 1.6070965147455867, bias: -2.4509314371098387, loss: 0.5014798543715647 epochs:200
w1: 4.208446138372673, w2: 1.6784291593155787, bias: -2.916046140900891, loss: 0.4775000442917141 epochs:300
w1: 5.037001920575126, w2: 1.7150020661272505, bias: -3.2863603614531667, loss: 0.4609135332893865 epochs:400
w1: 5.7361370030971806, w2: 1.7438715948521666, bias: -3.5968405908781333, loss: 0.4491370476635783 epochs:500
Final Weights: w1: 5.7361370030971806, w2: 1.7438715948521666, bias: -3.5968405908781333

In [18]:
custom_model.evaluate(x_test)

7     0.461288
21    0.108569
5     0.795641
2     0.699100
13    0.126379
19    0.305665
dtype: float64